export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
}
